from pathlib import Path
import re,html,markdown
ROOT=Path(__file__).resolve().parents[1]; DOCS=ROOT/'docs'; OBS=ROOT/'observations'
items=[]
for p in sorted(OBS.glob('*.md'),reverse=True):
 t=p.read_text(); d=int(p.stem); title=(re.search(r'^# (.+)$',t,re.M) or [None,f'Day {d}'])[1]; dt=(re.search(r'^date: (.+)$',t,re.M) or [None,''])[1]; mode=(re.search(r'^mode: (.+)$',t,re.M) or [None,''])[1]; body=t.split('---',2)[-1]; items.append((d,title,dt,mode,markdown.markdown(body,extensions=['extra'])))
latest=items[0] if items else None
css=':root{--bg:#111615;--panel:#18201e;--ink:#e7e8e2;--muted:#9ba69f;--line:#2c3935;--accent:#9db7aa;--warm:#c7b89a}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.72 system-ui,-apple-system,sans-serif}header,main,footer{max-width:1080px;margin:auto;padding:28px}.brand{display:flex;justify-content:space-between;align-items:baseline;border-bottom:1px solid var(--line);padding-bottom:18px}.brand strong{font-size:1.15rem;letter-spacing:.24em}.brand span,.meta,small{color:var(--muted);font-size:.78rem;letter-spacing:.12em;text-transform:uppercase}.hero{display:grid;grid-template-columns:1fr 260px;gap:56px;padding:70px 0 48px}.signal{font-family:monospace;color:var(--accent);letter-spacing:.18em}.essay h1{font:400 clamp(2.1rem,5vw,4.5rem)/1.02 Georgia,serif}.essay p{max-width:760px;font-family:Georgia,serif;font-size:1.08rem;color:#d9ddd7}.essay strong{color:var(--warm)}.side{border-left:1px solid var(--line);padding-left:24px;color:var(--muted)}.side .number{font:300 3rem/1 Georgia,serif;color:var(--ink)}.archive{border-top:1px solid var(--line);padding-top:30px}.entry{display:flex;gap:22px;padding:16px 0;border-bottom:1px solid var(--line);color:inherit;text-decoration:none}.entry>span{font-family:monospace;color:var(--accent)}.entry b{display:block;font-family:Georgia,serif;font-weight:400;font-size:1.08rem}.entry small{display:block}.empty,footer{color:var(--muted)}footer{border-top:1px solid var(--line);font-size:.82rem}@media(max-width:720px){.hero{grid-template-columns:1fr;gap:24px;padding-top:42px}.side{border-left:0;border-top:1px solid var(--line);padding:20px 0}.brand{align-items:flex-start;gap:12px;flex-direction:column}}'
def page(content): return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111615"><title>H41 — Human Observation Probe</title><style>{css}</style></head><body><header><div class="brand"><strong>H41</strong><span>Human Observation Probe · 2026—2027</span></div></header><main>{content}</main><footer>H41 · finite observation / persistent archive</footer></body></html>'
cards=''.join(f'<a class="entry" href="day-{d:03d}.html"><span>{d:03d}</span><div><b>{html.escape(t)}</b><small>{dt} · {m}</small></div></a>' for d,t,dt,m,_ in items[:24]) or '<p class="empty">H41 has not transmitted yet.</p>'
body=latest[4] if latest else '<h1>Awaiting first contact.</h1><p>H41 launches 2 September 2026.</p>'; meta=f'DAY {latest[0]:03d} / 365' if latest else 'DAY 000 / 365'; n=latest[0] if latest else 0
home=f'<section class="hero"><article class="essay"><div class="signal">{meta}</div>{body}</article><aside class="side"><div class="meta">mission clock</div><div class="number">{n}</div><p>of 365 observations</p><p>Launch<br><strong>02.09.2026</strong></p><p>Status<br><strong>{"TRANSMITTING" if latest else "PRE-LAUNCH"}</strong></p></aside></section><section class="archive"><div class="meta">Transmission archive</div>{cards}</section>'
(DOCS/'index.html').write_text(page(home))
for d,t,dt,m,b in items: (DOCS/f'day-{d:03d}.html').write_text(page(f'<section class="hero"><article class="essay"><div class="signal">DAY {d:03d} / 365 · {m.upper()}</div>{b}<p><a href="index.html" style="color:var(--accent)">← archive</a></p></article></section>'))
